create table Questions(
    "id" integer primary key autoincrement,
    "ques" text,
    "a" varchar(255),
    "b" varchar(255),
    "c" varchar(255),
    "d" varchar(255),
    "ans" integer
);

insert into Questions("ques","a","b","c","d","ans") values
("A train running at the speed of 60 km/hr crosses a pole in 9 seconds. What is the length of the train?","120 metres","180 metres","324 metres","150 metres",3),
("A train 125 m long passes a man, running at 5 km/hr in the same direction in which the train is going, in 10 seconds. The speed of the train is:","45 km/hr","50 km/hr","54 km/hr","55 km/hr",1),
("Two trains running in opposite directions cross a man standing on the platform in 27 seconds and 17 seconds respectively and they cross each other in 23 seconds. The ratio of their speeds is:","1 : 3","3 : 2","3 : 4","None of these",1),
("Two goods train each 500 m long, are running in opposite directions on parallel tracks. Their speeds are 45 km/hr and 30 km/hr respectively. Find the time taken by the slower train to pass the driver of the faster one.","12 sec","24 sec","48 sec","60 sec",1),
("Mr. Thomas invested an amount of Rs. 13,900 divided in two different schemes A and B at the simple interest rate of 14% p.a. and 11% p.a. respectively. If the total amount of simple interest earned in 2 years be Rs. 3508, what was the amount invested in Scheme B?","Rs. 6400","Rs. 6500","Rs. 7200","Rs. 7500",0),
("A lent Rs. 5000 to B for 2 years and Rs. 3000 to C for 4 years on simple interest at the same rate of interest and received Rs. 2200 in all from both of them as interest. The rate of interest per annum is:","5%","8%","10%","7%",2),
("A man took loan from a bank at the rate of 12% p.a. simple interest. After 3 years he had to pay Rs. 5400 interest only for the period. The principal amount borrowed by him was:","Rs. 2000","Rs. 10,000","Rs. 15,000","Rs. 20,000",2),
("What will be the ratio of simple interest earned by certain amount at the same rate of interest for 6 years and that for 9 years?","1 : 3","1 : 4","2 : 3","Data inadequate",2),
("A person borrows Rs. 5000 for 2 years at 4% p.a. simple interest. He immediately lends it to another person at 6% p.a for 2 years. Find his gain in the transaction per year.","Rs. 112.50","Rs. 125","Rs. 225","Rs. 167.50",0),
("The cost price of 20 articles is the same as the selling price of x articles. If the profit is 25%, then the value of x is:","16","15","19","23",0),
("A vendor bought toffees at 6 for a rupee. How many for a rupee must he sell to gain 20%?","3","4","5","6",2),
("A shopkeeper expects a gain of 22.5% on his cost price. If in a week, his sale was of Rs. 392, what was his profit?","Rs. 18.20","Rs. 70","Rs. 72","Rs. 88.25",2),
("A man buys a cycle for Rs. 1400 and sells it at a loss of 15%. What is the selling price of the cycle?","Rs. 1090","Rs. 1160","Rs. 1190","Rs. 1202",2),
("On selling 17 balls at Rs. 720, there is a loss equal to the cost price of 5 balls. The cost price of a ball is:","Rs. 45","Rs. 50","Rs. 55","Rs. 60",3),
("A trader mixes 26 kg of rice at Rs. 20 per kg with 30 kg of rice of other variety at Rs. 36 per kg and sells the mixture at Rs. 30 per kg. His profit percent is:","No profit, no loss","5%","8%","10%",1),
("A can do a work in 15 days and B in 20 days. If they work on it together for 4 days, then the fraction of the work that is left is :","1/4","1/10","7/15","8/15",3),
("A alone can do a piece of work in 6 days and B alone in 8 days. A and B undertook to do it for Rs. 3200. With the help of C, they completed the work in 3 days. How much is to be paid to C?","Rs. 375","Rs. 400","Rs. 600","Rs. 800",1),
("A is 30% more efficient than B. How much time will they, working together, take to complete a job which A alone could have done in 23 days?","11 days","13 days","20 days","None of these",1),
("A, B and C can complete a piece of work in 24, 6 and 12 days respectively. Working together, they will complete the same work in:","1/24 days","7/24 days","24/7 days","5 days",2),
("Twenty women can do a work in sixteen days. Sixteen men can complete the same work in fifteen days. What is the ratio between the capacity of a man and a woman?","3:4","4:3","5:3","Data inadequate",1),
("A boat can travel with a speed of 13 km/hr in still water. If the speed of the stream is 4 km/hr, find the time taken by the boat to go 68 km downstream.","2 hrs","3 hrs","4 hrs","5 hrs",2),
("3, 5, 11, 14, 17, 21","21","17","14","3",2),
("8, 27, 64, 100, 125, 216, 343","27","100","125","343",1),
("10, 14, 16, 18, 21, 24, 26","26","24","21","18",2),
("835, 734, 642, 751, 853, 981, 532","751","853","981","532",0),
("The sum of ages of 5 children born at the intervals of 3 years each is 50 years. What is the age of the youngest child?","4 years","8 years","10 years","None of these",0),
("A is two years older than B who is twice as old as C. If the total of the ages of A, B and C be 27, then how old is B?","7","8","9","10",3),
("The age of father 10 years ago was thrice the age of his son. Ten years hence, father's age will be twice that of his son. The ratio of their present ages is:","5 : 2","7 : 3","9 : 2","13 : 4",1),
("Find the greatest number that will divide 43, 91 and 183 so as to leave the same remainder in each case.","4","7","9","13",0),
("Six bells commence tolling together and toll at intervals of 2, 4, 6, 8 10 and 12 seconds respectively. In 30 minutes, how many times do they toll together ?","4","10","15","16",3),
("The greatest number of four digits which is divisible by 15, 25, 40 and 75 is:","9000","9400","9600","9800",2),
("Reduce 128352/238368 to its lowest terms.","3/4","5/13","7/13","9/13",2),
("Which of the following has the most number of divisors?","99","101","176","182",2),
("A, B and C jointly thought of engaging themselves in a business venture. It was agreed that A would invest Rs. 6500 for 6 months, B, Rs. 8400 for 5 months and C, Rs. 10,000 for 3 months. A wants to be the working member for which, he was to receive 5% of the profits. The profit earned was Rs. 7400. Calculate the share of B in the profit.","Rs. 1900","Rs. 2660","Rs. 2800","Rs. 2840",1),
("Arun, Kamal and Vinay invested Rs. 8000, Rs. 4000 and Rs. 8000 respectively in a business. Arun left after six months. If after eight months, there was a gain of Rs. 4005, then what will be the share of Kamal?","Rs. 890","Rs. 1335","Rs. 1602","Rs. 1780",0),
("A and B started a partnership business investing some amount in the ratio of 3 : 5. C joined then after six months with an amount equal to that of B. In what proportion should the profit at the end of one year be distributed among A, B and C?","3 : 5 : 2","3 : 5 : 5","6 : 10 : 5","Data inadequate",2),
("Two numbers are respectively 20% and 50% more than a third number. The ratio of the two numbers is:","2:5","3:5","4:5","6:7",2),
("A sum of money is to be distributed among A, B, C, D in the proportion of 5 : 2 : 4 : 3. If C gets Rs. 1000 more than D, what is B's share?","Rs. 500","Rs. 1500","Rs. 2000","None of these",2),
("In a mixture 60 litres, the ratio of milk and water 2 : 1. If this ratio is to be 1 : 2, then the quantity of water to be further added is:","20 litres","30 litres","40 litres","60 litres",3),
("The ratio between the perimeter and the breadth of a rectangle is 5 : 1. If the area of the rectangle is 216 sq. cm, what is the length of the rectangle?","16 cm","18 cm","24 cm","Data inadequate",1),
("The percentage increase in the area of a rectangle, if each of its sides is increased by 20% is:","40%","42%","44%","46%",2),
("From a group of 7 men and 6 women, five persons are to be selected to form a committee so that at least 3 men are there on the committee. In how many ways can it be done?","564","645","735","756",3),
("How many 3-digit numbers can be formed from the digits 2, 3, 5, 6, 7 and 9, which are divisible by 5 and none of the digits is repeated?","5","10","15","20",3);